### ISSUE TITLE
How to Distribute Source Code

### ISSUE THREAD

**Issue by kemitchell** [licensezero/licensezero-reciprocal-public-license#2]
Early drafts only required that licensees "publish" their source code. That's since evolved to "publishing it, in the preferred form for making changes, to a freely accessible distribution system widely used for similarly licensed source code."

That privileges popular services, and also ensconces freemium distribution. But how we distribute open source is as much subject to change as how we write it in the first place.

On the one hand, requiring just "publication" makes it easy for licensors to publish where they expect it may never be found. On the other hand, requiring something specific, like sending changes back to the licensors (who may be legion) or to a specific service identified by URL, become brittle and overcomplicated.

The current language is a shot as a happy medium. But I'd sure like to find a happier one, if I could.

**Comment by anseljh** [comment]
It only "ensconces freemium distribution" if freemium distribution remains popular. If instead everyone decides to publish code on their own Raspberry Pis, then that qualifies. I think this is a good compromise.
